### PR TITLE
Adds search field options

### LINKED ISSUE #43: Search box below apps list
Hello,

Great launcher, thank you for your work!

It might be useful to allow placing the "Search apps" box of the app drawer at the bottom instead of on top, that way it could be easier to tap it to type the name of an app (just like the new Firefox for Android versions have been doing recently).

Thanks again!

### LINKED ISSUE #62: Hide search field
Make it possible to hide the search field.

### PR DESCRIPTION
**Pull request by hayribakici**
Fixes #62, fixes #43. This PR adds an additional option screen to hide and position the search field in the app drawer. Since the 'show keyboard' toggle is also part of this, it is grouped together with this new option (see screenshots). Once the 'Show search field' switch is turned off, the show keyboard option and positioning the search field are disabled.

On a technical level, I had to upgrade `protobuf` to (the current) version `3.23`, since the current version had problems wish the optional property.

I am also thinking to add a 'Reset to default' action for this screen. What do you think @jkuester ?

### CODE REVIEW

**Comment by hayribakici** [comment]
Returning to draft, because I found a bug with Android L

**Review by jkuester — APPROVED** [review]
:star_struck: This is great!  Thanks!

**Review by TobiTenno — APPROVED** [review]

**Comment by hayribakici** [comment]
@jkuester #138 fixes the `textColor` of the `SwitchCompat` buttons. This should also be applied in the new screens here. Should a new PR be created?

**Comment by TobiTenno** [comment]
> @jkuester #138 fixes the `textColor` of the `SwitchCompat` buttons. This should also be applied in the new screens here. Should a new PR be created?

go ahead and make a new one, you'll probably get it done before one of us would.

**Comment by neshant** [comment]
This is super cool ! when will this change be released on fdroid to use or how can I already use this , so excited about this change ! <3

**Comment by TobiTenno** [comment]
if you're running the fdroid build right now, you can't update with the self-signed one from the repo build. you'd have to uninstall your current local copy before you install the self-signed github one. (this is standard android behavior, not something specific to unlauncher)

**Comment by jkuester** [comment]
> when will this change be released on fdroid

There is not a hard date, but we are hoping to have a beta release released within days and a formal `2.1.0` release cut within a few weeks.  Normally, these releases will show up on the F-Droid repo 2-5 days after we cut them here on GitHub.

**Comment by neshant** [comment]
> if you're running the fdroid build right now, you can't update with the self-signed one from the repo build. you'd have to uninstall your current local copy before you install the self-signed github one. (this is standard android behavior, not something specific to unlauncher)

oh thank you so much I am not familiar with android apps signing process, after uninstalling the app I downloaded from fdroid I was able to install this apk which is self signed, thank you so much for explaining this.

**Pull request merged**
