### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by zepp**
Russian translation update (missed strings are added and items are reordered)

### CODE REVIEW

**Review by TobiTenno — CHANGES_REQUESTED** [review]
@zepp could you rebase so we can do a cleaner update?

**Comment by zepp** [comment]
@TobiTenno done

**Comment by TobiTenno** [comment]
could you do the options_fragment layout updates in a separate PR so we can keep this one just the lang updates? i'll work on the layout updates immediately after the translation updates are in (as fast as I see them) to avoid any weird layouts for russian

**Comment by TobiTenno** [comment]
@zepp could you do the options_fragment layout updates in a separate PR so we can keep this one just the lang updates? i'll work on the layout updates immediately after the translation updates are in (as fast as I see them) to avoid any weird layouts for russian

**Comment by zepp** [comment]
@TobiTenno no problem, it is done.

**Comment by zepp** [comment]
@TobiTenno it seems that @khwolf has already fixed the issue with TextView's width so I don't need to make another PR.

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
