### PR TITLE
Add popup menu for apps in the drawer

### PR DESCRIPTION
**Pull request by ru2saig**
Addresses #69.

signal-2022-12-11-132646_002

### CODE REVIEW

**Comment by Nikl174** [comment]
If it works correctly, i would appreciate to see this feature on the mein release, maybe i will test it on the weekend on my phone. Thanks in advance  @ru2saig for taking the time implementing it <3

**Comment by Nikl174** [comment]
Finally found some time building it and it work, very nice :D, finally easy uninstall, rename etc. <3
Everything seams to work fine, going to test it further in the next weeks.  

One thing i notice, **i couldn't install the release build, only the debug one**, not sure y though... Could you install the release build?

(And the keyboard bug #127 is also present, but this is another workspace.) 
Again thx @ru2saig I hope this PR is merged soon

**Comment by ru2saig** [comment]
Really? Do you have more details? I'm using v3.1.1-ruusaig from the releases page.

**Review by jkuester — APPROVED** [review]
I am sorry for the absurd delay in reviewing this!  Thank you for this excellent contribution!  :tada:

**Comment by fusaty** [comment]
Hi, is this feature part of the F-droid release, I would like to use it but it isnt working for me.

**Pull request merged**
