### PR TITLE
feat(#103): make hidden apps findable with search

### LINKED ISSUE #103: Browse hidden apps
Make it possible to browse the hidden apps without unhiding them.

### PR DESCRIPTION
**Pull request by JuanJakobo**
Hi jkuester,
Thanks for the great app!
I created a method to enable in the settings the option to search all apps (shown and hidden).
Hope it is the correct way to do it.

closes #103

### CODE REVIEW

**Comment by jkuester** [comment]
@JuanJakobo I am sorry for the delayed response here!  Could you help me understand the rational behind this feature?  It seems like if you want to see all the apps in the drawer, then just do not hide any of the apps via the "Visible Apps" menu.  If you also want to see the pinned "home apps" in the drawer, these are hidden by default when you pin them to the home screen.  But, you can actually use the "Visible Apps" menu and re-check them so they are displayed in the drawer again (and are searchable).  

But, maybe I am missing what you are trying to do here! :thinking:

**Comment by JuanJakobo** [comment]
Hi,
the idea here is that you can hide apps as you said via the "Visible Apps", but you might still want to search all apps. For example I hide some apps from the drawer as the list gets to crowed. This app for example could be WhatsApp. I still want to use WhatsApp and going to the apps overview in Android Settings just to open the app is a bit to much work. Therefore I would like to search for it using the "Search Bar" above the drawer. So the App is hidden from the drawer itself, but it will appear in the search results. 

Hope that makes it clear. :smile:

**Comment by hayribakici** [comment]
This PR fixes #103

**Comment by C4yrslf** [comment]
I wholeheartedly agree with JuanJakobo. On the pixel 6a, the drawer can fit about 19 apps which is good. But excluding the apps on the home screen, I have maybe25 apps that should be in the drawer. 

What happens then is the drawer can be scrolled. This is, for me, a small irritation sometimes as I use my phone mostly with muscle memory and I can't for the apps in the drawer as with the scrolling feature, apps are not always at the location on the screen.

The solution for this is to be able to search all apps with the search function. It keeps the drawer organized and clean while still allowing access to all apps, including those I decided not to put in the drawer for the reason mentionned above.

I love this app, thank you.

**Review by jkuester — APPROVED** [review]
Many thanks @JuanJakobo for this functionality!  I had to tweak things a bit to get this into the latest codebase, but I think that made things even more streamlined!

**Pull request merged**
